### ISSUE TITLE
More contrast for text selection

### ISSUE THREAD

**Issue by pkaske** [robb0wen/synthwave-vscode#2] opened 2019-04-29 17:25 UTC
Hi! I love your theme! It's sooo awesome.
The only thing I don't find optimal is how subtle selected text is highlighted.
Maybe it appears to me like that because of my screens but I thought wanted to give that feedback anyways.

**Comment by kokarn** [comment] 2019-04-29 17:31
Duplicate of #1  :D

**Closed** 2019-04-30 07:58 UTC
