### ISSUE TITLE
Extension doesn't glow last days

### ISSUE THREAD

**Issue by GeorgiNiagulov** [robb0wen/synthwave-vscode#281] opened 2022-11-23 09:45 UTC
Hi, extension doesn't glow last days after update 
I follow steps:
1.Restart after enable neon dreams
2.Fix checksums
![issue](https://user-images.githubusercontent.com/49201016/203515222-93c070cd-88ce-487b-baac-3df6415c56a2.png)

**Comment by novym** [comment] 2022-12-07 20:53
+1 Glow no longer working after update
```
Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:43:37.594Z (2 days ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No
```

**Comment by lourain** [comment] 2022-12-08 01:35
yes. I also have the same problem when vscode update to v1.74

**Comment by HectorCode8** [comment] 2022-12-08 02:54
confirm. not working.

**Comment by MichaelAmadheo** [comment] 2022-12-08 04:40
I'm Using VScode v1.74 and the glow is not working

**Comment by tiruns** [comment] 2022-12-08 05:07
It looks like the ".vscode-tokens-styles" element may contain some default value instead of being empty, which triggers the theme to initialize too early.

A temporary workaruond might be like:
[VSCode Dir]\resources\app\out\vs\code\electron-sandbox\workbench\neondreams.js:164
```
// does it have content ?
const tokenStyles = document.querySelector('.vscode-tokens-styles').innerText
  && document.querySelector('.vscode-tokens-styles').innerText !== ''
  && document.querySelector('.vscode-tokens-styles').innerText.includes(".mtk7");
```

**Comment by WRangers** [comment] 2022-12-08 06:01
> It looks like the ".vscode-tokens-styles" element may contain some default value instead of being empty, which triggers the theme to initialize too early.
> 
> A temporary workaround might be like: [VSCode Dir]\resources\app\out\vs\code\electron-sandbox\workbench\neondreams.js:164
> 
> ```
> // does it have content ?
> const tokenStyles = document.querySelector('.vscode-tokens-styles').innerText
>   && document.querySelector('.vscode-tokens-styles').innerText !== ''
>   && document.querySelector('.vscode-tokens-styles').innerText.includes(".mtk7");
> ```
> 
> You may also need to restart the vscode app to make the modification take effect.

It works! Thanks!

**Comment by AppeliusTheo** [comment] 2022-12-08 13:57
> It looks like the ".vscode-tokens-styles" element may contain some default value instead of being empty, which triggers the theme to initialize too early.
> 
> A temporary workaround might be like: [VSCode Dir]\resources\app\out\vs\code\electron-sandbox\workbench\neondreams.js:164
> 
> ```
> // does it have content ?
> const tokenStyles = document.querySelector('.vscode-tokens-styles').innerText
>   && document.querySelector('.vscode-tokens-styles').innerText !== ''
>   && document.querySelector('.vscode-tokens-styles').innerText.includes(".mtk7");
> ```
> 
> You may also need to restart the vscode app to make the modification take effect.

It works, thanks ! And for those who ask about Ubuntu, the path is `~/.vscode/extensions/robbowen.synthwave-vscode-0.1.14/src/js/theme_template.js`

**Comment by HectorCode8** [comment] 2022-12-08 18:57
> It looks like the ".vscode-tokens-styles" element may contain some default value instead of being empty, which triggers the theme to initialize too early.
> 
> A temporary workaround might be like: [VSCode Dir]\resources\app\out\vs\code\electron-sandbox\workbench\neondreams.js:164
> 
> ```
> // does it have content ?
> const tokenStyles = document.querySelector('.vscode-tokens-styles').innerText
>   && document.querySelector('.vscode-tokens-styles').innerText !== ''
>   && document.querySelector('.vscode-tokens-styles').innerText.includes(".mtk7");
> ```
> 
> You may also need to restart the vscode app to make the modification take effect.

Ty. Works for me.!!

**Comment by robb0wen** [comment] 2022-12-08 19:03
Thanks all for the feedback and triage! I've been busy with a client work recently so haven't had a lot of time to devote to a new release, but I'll get it on asap

**Comment by marvel-srikant** [comment] 2022-12-09 02:59
# After the November 2022 Update (version 1.74) text is not glowing.
![image](https://user-images.githubusercontent.com/52560067/206614098-b50f3b8b-8f39-472f-8200-6a3fb2ef8700.png)

 **It was working fine yesterday but after the update the text is not glowing.**

**Comment by juamperuiz** [comment] 2022-12-09 08:37
The solution of @tiruns is working fine at 9th december in vscode version 1.74.
Thanks so much!

**Comment by EvilCult** [comment] 2022-12-09 09:03
> It looks like the ".vscode-tokens-styles" element may contain some default value instead of being empty, which triggers the theme to initialize too early.
> 
> A temporary workaround might be like: [VSCode Dir]\resources\app\out\vs\code\electron-sandbox\workbench\neondreams.js:164
> 
> ```
> // does it have content ?
> const tokenStyles = document.querySelector('.vscode-tokens-styles').innerText
>   && document.querySelector('.vscode-tokens-styles').innerText !== ''
>   && document.querySelector('.vscode-tokens-styles').innerText.includes(".mtk7");
> ```
> 
> You may also need to restart the vscode app to make the modification take effect.

works for me,thanks a lot!!!!

**Comment by Kapral67** [comment] 2022-12-09 11:44
> It looks like the ".vscode-tokens-styles" element may contain some default value instead of being empty, which triggers the theme to initialize too early.
> 
> A temporary workaround might be like: [VSCode Dir]\resources\app\out\vs\code\electron-sandbox\workbench\neondreams.js:164
> 
> ```
> // does it have content ?
> const tokenStyles = document.querySelector('.vscode-tokens-styles').innerText
>   && document.querySelector('.vscode-tokens-styles').innerText !== ''
>   && document.querySelector('.vscode-tokens-styles').innerText.includes(".mtk7");
> ```
> 
> You may also need to restart the vscode app to make the modification take effect.

Confirmed to work as well on 6.0.11-arch1-1
[VSCode Dir] should be /opt/visual-studio-code

**Comment by 3v3L1na** [comment] 2022-12-09 14:31
How can I make it work on Mac operating system?

**Comment by briggleman** [comment] 2022-12-09 17:10
> ~/.vscode/extensions/robbowen.synthwave-vscode-

as noted above, navigate to `/.vscode/extensions/robbowen.synthwave-vscode-0.1.14/src/js/theme_template.js` and add the additional line of code.

**Comment by robb0wen** [comment] 2022-12-09 17:59
Thanks all! As @tiruns said, the fix above will work temporarily but the .mtk classes are generated by VScode and they do sometimes change (this happened in the past and broke the colour scheme).

That said, the workaround pointed me straight to the cause of the issue, so massive thanks to @tiruns! 🙌

Last night I rewrote all of the bootstrap checks to be a bit more resilient - Before trying to replace the styles, the script now checks that all of the synthwave theme colours are present in the workbench dom styles. If the styles aren't there, it will try again the next time they update.

Anyhow, I did a local build of the fix and have been running it all day today. I haven't had any issues, so I'll try to tidy up the code a bit and push out a new version later this evening.

**Comment by robb0wen** [comment] 2022-12-09 18:30
v0.1.15 is now available from the VS Code marketplace. 🎉🚀
As always with updates: 

1. Run the Disable Neon Dreams function from the command palette
2. Uninstall the extension completely.
3. Install the updated version of the extension (now v0.1.15)
4. Run the Enable Neon Dreams function from the command palette.

VScode has so many moving parts that rescuing this theme when it breaks is often way more difficult than it should be. Thanks for all the help in figuring this one out - I really appreciate it.

**Comment by 3v3L1na** [comment] 2022-12-09 18:40
> v0.1.15 is now available from the VS Code marketplace. 🎉🚀 As always with updates:
> 
> 1. Run the Disable Neon Dreams function from the command palette
> 2. Uninstall the extension completely.
> 3. Install the updated version of the extension (now v0.1.15)
> 4. Run the Enable Neon Dreams function from the command palette.
> 
> VScode has so many moving parts that rescuing this theme when it breaks is often way more difficult than it should be. Thanks for all the help in figuring this one out - I really appreciate it.

Wow thank you so so much! 
I was so sad when I discovered my theme wasn't glowing and I was hoping it would. It's a favourite of mine, I can't code when it doesn't glow 🤣

It feels like characters and strings are dancing at the rhythm of my fingers. Super happy it's working now.

**Comment by marvel-srikant** [comment] 2022-12-10 01:42
@3v3L1na

**Comment by marvel-srikant** [comment] 2022-12-10 01:45
# Thank you so much @robb0wen. 
---
Now I can work again.
![image](https://user-images.githubusercontent.com/52560067/206822655-8e530887-350f-4116-b603-86a7ba780954.png)

**Comment by GeorgiNiagulov** [comment] 2022-12-12 08:40
Thank you @robb0wen. It's working now.

**Comment by robb0wen** [comment] 2022-12-13 10:53
Thanks all! I'll close this and keep my fingers crossed that the next VS code update doesn't change too much 😅

**Closed by robb0wen** 2022-12-13 10:53 UTC
