### ISSUE TITLE
neon dreams error 

### ISSUE THREAD

**Issue by vcancode** [robb0wen/synthwave-vscode#322] opened 2024-10-06 07:24 UTC
my neon dreams is not working in synthwave in vscode it says - 

Command 'Synthwave '84: Enable Neon Dreams' resulted in an error
Cannot read properties of undefined (reading 'filename')
![Screenshot 2024-10-06 125142](https://github.com/user-attachments/assets/9d866653-c942-4918-a01e-1dce23185751)

**Comment by SetRedEyes** [comment] 2024-10-06 19:37
Same error on Mac

**Comment by kmichalski0** [comment] 2024-10-07 09:26
I got this as well. It happened after the most recent Visual Code update. What a bummer

**Comment by robb0wen** [comment] 2024-10-07 10:07
The latest VS code has changed something fundamental in how the workbench is loading which has broken the glow. I don't have a lot of time right now due to work commitments, but I'll take a look into how it might be fixable.

**Comment by robb0wen** [comment] 2024-10-07 10:08
Duplicate of #320

**Closed by robb0wen** 2024-10-07 10:08 UTC
