### ISSUE TITLE
Synthwave84 error VS Code Windows 11

### ISSUE THREAD

**Issue by AgGro00** [robb0wen/synthwave-vscode#319] opened 2024-10-03 23:13 UTC
I got this message error when I gonna enable Synthwave84 "neon dreams"  

I have already reinstalled the theme but it does not solve the problem

![Untitled](https://github.com/user-attachments/assets/d86eee86-2d5a-45a0-99e9-a4833e9cfd2e)

**Comment by jruizsulime** [comment] 2024-10-04 06:25
yep, today its seen that last vscode update broke neon dreams feature

**Comment by vacnex** [comment] 2024-10-04 16:17
Same
![image](https://github.com/user-attachments/assets/cfd55552-a7bf-45f6-a21e-0997cae81d9e)

**Comment by AnderCMD** [comment] 2024-10-04 16:43
I was looking for this problem and at the moment there is no current solution, the problem was generated from the last update of vscode, this happens both in MacOS and Windows

Version: 1.94.0 (Universal)

<img width="295" alt="image" src="https://github.com/user-attachments/assets/3340a754-d8d7-4fb1-b689-009f42500eb9">

**Comment by robb0wen** [comment] 2024-10-07 10:27
duplicate of #320

**Comment by robb0wen** [comment] 2024-10-07 10:27
Duplicate of #320

**Closed by robb0wen** 2024-10-07 10:27 UTC
