### ISSUE TITLE
Selecting in multiple lines extends highlight beyond selection 

### ISSUE THREAD

**Issue by fmajestic** [robb0wen/synthwave-vscode#153] opened 2020-03-04 11:07 UTC
When selecting within a single line, the highlight is displayed correctly:
![sc1](https://user-images.githubusercontent.com/32621614/75872990-6d548f00-5e0f-11ea-86c8-cb76cc0de6b7.png)

Selecting within multiple lines makes the highlight extend to one character before and after the selection. This is visual only, copying the text doesn't copy those extra highlighted characters.
![sc2](https://user-images.githubusercontent.com/32621614/75873242-db995180-5e0f-11ea-9367-8160a84b1c6b.png)

This does not happen when the glow is disabled (still using the theme):
![sc3](https://user-images.githubusercontent.com/32621614/75873682-9fb2bc00-5e10-11ea-801a-cf9949d798ee.png)

**Comment by Zzombiee2361** [comment] 2020-04-13 09:15
Ok, I found the problem, I think. So this is caused by [this style on editor_chrome.css](https://github.com/robb0wen/synthwave-vscode/blob/d2a7f6aa73628e37df09de8647ca2c61f617435c/src/css/editor_chrome.css#L1-L3). Removing that style will fix the problem, but I don't know what they're for and why is it becoming a problem just now.  
If you want to try removing it now (and see if it causes other problem), you can edit `%CODE%/resources/app/out/vs/code/electron-browser/workbench/neondreams.js`. `%CODE%` is your installation path (mine is `/usr/share/code`). The style is around line 53, remove it and restart VS Code.

**Comment by lilyball** [comment] 2021-02-10 21:57
Thank you for figuring this out! This has been really bugging me. @robb0wen any chance on getting this merged (or an explanation of what the selector was for)?

**Closed** 2021-09-28 12:54 UTC
