### ISSUE TITLE
admin privilleges

### ISSUE THREAD

**Issue by GeorgiNiagulov** [robb0wen/synthwave-vscode#263] opened 2022-07-13 07:54 UTC
I updated vs code insiders on 8 july. And when I enable synthwave84 neon dreams, I receive this message "You must run VS code with admin privileges in order to enable Neon Dreams.". I written to vscode insiders github, they responded this problem to extension.

**Comment by pulberg** [comment] 2022-07-13 20:43
Same issue - 

macOS 12.4

vscode - 
Version: 1.70.0-insider (Universal)
Commit: 052d5b0027f6c9d64c8ca35955cb5117ba94d5d7
Date: 2022-07-13T05:21:34.551Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

**Comment by JediRhymeTrix** [comment] 2022-07-14 17:15
I'm also facing the same issue. 

I've tried the solution suggested in #146 but it didn't work.

The suggested fix is to run:

`sudo chmod ugo+rw /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench`

However, `workbench` is not present inside `electron-browser` in the newer Insider builds. So, if the theme looks for it in that directory, it will error out. I have not gone through the code, but could this be the root cause of the issue?

**Comment by mcpads** [comment] 2022-07-16 07:55
In lastest macOS VSCode Insider, path ```/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/workbench``` moves to ```/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench``` for some reasons.

I checked that the extension works well if all ```electron-browser``` in below lines is replaced with ```electron-sandbox```, for Insider.

https://github.com/robb0wen/synthwave-vscode/blob/07273cd1e1fb6d0873dd96ab9f2e291eb136bee5/src/extension.js#L30-L40

https://github.com/robb0wen/synthwave-vscode/blob/07273cd1e1fb6d0873dd96ab9f2e291eb136bee5/src/extension.js#L109-L113

**Comment by vinayakkulkarni** [comment] 2022-07-29 14:42
> This issue is caused by changed behavior of latest Visual Studio Code.
> 
> Basically this extension is enabled by changing workbench files of `electron-browser` in VSCode app. However, `electron-browser` was removed in commit [microsoft/vscode@`f4f1b04`](https://github.com/microsoft/vscode/tree/f4f1b04d872a2b94d9a5105a1eefb81a213c07f2), and it was moved to `electron-sandbox`.
> 
> I checked that the extension works well if all `electron-browser` in below lines is replaced with `electron-sandbox`, for Insider.
> 
> https://github.com/robb0wen/synthwave-vscode/blob/07273cd1e1fb6d0873dd96ab9f2e291eb136bee5/src/extension.js#L30-L40
> 
> https://github.com/robb0wen/synthwave-vscode/blob/07273cd1e1fb6d0873dd96ab9f2e291eb136bee5/src/extension.js#L109-L113

Can confirm replacing `electron-browser` with `electron-sandbox` worked! Thanks!

**Comment by mirulnasir** [comment] 2022-08-05 00:45
had this issue today. confirmed replacing electron-browser with electron-sandbox worked. thank you.

**Comment by puentebravo** [comment] 2022-08-05 01:03
Just had this issue after updating VSCode, and the suggested changes worked. Thank you!

**Comment by FrancRose** [comment] 2022-08-05 01:04
> Just had this issue after updating VSCode, and the suggested changes worked. Thank you!

Newb here, where do you go to change these settings?

**Comment by puentebravo** [comment] 2022-08-05 01:10
> > Just had this issue after updating VSCode, and the suggested changes worked. Thank you!
> 
> Newb here, where do you go to change these settings?

If you're on Windows, head to the directory VSCode is installed in (.vscode by default, typically under users/yourUsername), then head into the extensions directory. 

Once you're there, you're looking for a folder called 'robbowen.synthwave-vscode-0.1.11'. Inside, navigate to the src folder, then pop open extension.js in your code editor of choice. The code you need to change is on the lines specified in @vinayakkulkarni 's comment above.

**Comment by yowynn** [comment] 2022-08-05 03:07
> > This issue is caused by changed behavior of latest Visual Studio Code.
> > Basically this extension is enabled by changing workbench files of `electron-browser` in VSCode app. However, `electron-browser` was removed in commit [microsoft/vscode@`f4f1b04`](https://github.com/microsoft/vscode/tree/f4f1b04d872a2b94d9a5105a1eefb81a213c07f2), and it was moved to `electron-sandbox`.
> > I checked that the extension works well if all `electron-browser` in below lines is replaced with `electron-sandbox`, for Insider.
> > https://github.com/robb0wen/synthwave-vscode/blob/07273cd1e1fb6d0873dd96ab9f2e291eb136bee5/src/extension.js#L30-L40
> > 
> > https://github.com/robb0wen/synthwave-vscode/blob/07273cd1e1fb6d0873dd96ab9f2e291eb136bee5/src/extension.js#L109-L113
> 
> Can confirm replacing `electron-browser` with `electron-sandbox` worked! Thanks!

that works, my code version is: 1.70.0
thanks a lot

**Comment by ODYYYYYY** [comment] 2022-08-05 13:18
> > > Just had this issue after updating VSCode, and the suggested changes worked. Thank you!
> > 
> > 
> > Newb here, where do you go to change these settings?
> 
> If you're on Windows, head to the directory VSCode is installed in (.vscode by default, typically under users/yourUsername), then head into the extensions directory.
> 
> Once you're there, you're looking for a folder called 'robbowen.synthwave-vscode-0.1.11'. Inside, navigate to the src folder, then pop open extension.js in your code editor of choice. The code you need to change is on the lines specified in @vinayakkulkarni 's comment above.

It works well, thank you a lot !

**Comment by nadinCodeHat** [comment] 2022-08-05 14:15
I wrote a medium blog on how to activate the neon dreams without admin privileges
[Here’s how to install the SynthWave ’84 theme and activate the glow effect (Neon Dreams) in VS Code](https://medium.com/@nadinCodeHat/heres-how-to-install-the-synthwave-84-theme-and-activate-the-glow-effect-neon-dreams-in-vs-code-315ceeeacd39)

**Comment by quantumudit** [comment] 2022-08-05 20:04
This worked. Finally after hours of head scratching .. Thanks a lot.

**Comment by codeMauguin** [comment] 2022-08-07 02:28
> > 此问题是由最新 Visual Studio Code 的行为更改引起的。
> > 基本上，这个扩展是通过更改`electron-browser`VSCode 应用程序中的工作台文件来启用的。但是，`electron-browser`在提交[microsoft/vscode@`f4f1b04`](https://github.com/microsoft/vscode/tree/f4f1b04d872a2b94d9a5105a1eefb81a213c07f2)中被删除，并被移至`electron-sandbox`.
> > `electron-browser`如果以下行中的所有内容都被替换`electron-sandbox`为 Insider，我检查了扩展是否正常工作。
> > https://github.com/robb0wen/synthwave-vscode/blob/07273cd1e1fb6d0873dd96ab9f2e291eb136bee5/src/extension.js#L30-L40
> > 
> > https://github.com/robb0wen/synthwave-vscode/blob/07273cd1e1fb6d0873dd96ab9f2e291eb136bee5/src/extension.js#L109-L113
> 
> 可以确认替换`electron-browser`为`electron-sandbox`工作！谢谢！

我有个疑问为什么我的window上这里面的iswin是false

**Comment by hmmhmmhm** [comment] 2022-08-08 04:04
Has anyone solved it in the mac?

**Comment by nadinCodeHat** [comment] 2022-08-08 04:28
> Has anyone solved it in the mac?

Try to find the `.vscode\extensions` path in mac and locate synthwave84.css file and editing the settings.json 

`"vscode_custom_css.imports": [
   "file:///C:/Users/LENOVO/.vscode/extensions/robbowen.synthwave-      vscode-0.1.11/synthwave84.css"
]`

[Try the steps for mac probably it'll work](https://medium.com/@nadinCodeHat/heres-how-to-install-the-synthwave-84-theme-and-activate-the-glow-effect-neon-dreams-in-vs-code-315ceeeacd39)

**Comment by robb0wen** [comment] 2022-08-08 10:20
There was a [PR](https://github.com/robb0wen/synthwave-vscode/pull/264) to fix the issue, but I needed to add a check to prevent compatibility issues across the different VS code versions (pre and post 'electron-sandbox').

The latest changes on the PR looks like it's working on Mac. I don't have access to a windows machine right now though, so I'd be super grateful if a windows user could please test that everything works as expected with the version in that PR.

Once we're happy it's working on windows I'll merge it in and push a new version of the extension to the marketplace

**Comment by GeorgiNiagulov** [comment] 2022-08-08 10:29
I checked that everything works well if all electron-browser is replaced with electron-sandbox for Insiders on windows. I changed them in extension and there not any problems. Thankk you :)

**Comment by cheestudio** [comment] 2022-08-08 17:10
@robb0wen Another Windows user (Windows 11) confirming that the [PR](https://github.com/robb0wen/synthwave-vscode/pull/264) works for me, as well.

**Comment by itsnull12** [comment] 2022-08-08 17:28
> This issue is caused by changed behavior of latest Visual Studio Code.
> 
> Basically this extension is enabled by changing workbench files of `electron-browser` in VSCode app. However, `electron-browser` was removed in commit https://github.com/microsoft/vscode/tree/f4f1b04d872a2b94d9a5105a1eefb81a213c07f2, and it was moved to `electron-sandbox`.
> 
> I checked that the extension works well if all `electron-browser` in below lines is replaced with `electron-sandbox`, for Insider.
> 
> https://github.com/robb0wen/synthwave-vscode/blob/07273cd1e1fb6d0873dd96ab9f2e291eb136bee5/src/extension.js#L30-L40
> 
> https://github.com/robb0wen/synthwave-vscode/blob/07273cd1e1fb6d0873dd96ab9f2e291eb136bee5/src/extension.js#L109-L113

Thank u so much

**Comment by jdan** [comment] 2022-08-09 16:03
Confirmed on mac that changing all occurences of `electron-browser` to `electron-sandbox` inside `~/.vscode/extensions/robbowen.synthwave-vscode-0.1.11/src/extension.js` fixed the issue.

**Comment by bildungsroman** [comment] 2022-08-11 17:11
> Confirmed on mac that changing all occurrences of `electron-browser` to `electron-sandbox` inside `~/.vscode/extensions/robbowen.synthwave-vscode-0.1.11/src/extension.js` fixed the issue.

I tried this but am still getting the admin error. I reloaded VSCode, is there anything else I need to do to get this to work?

I'm on an M1, macOS 12.4.

**Comment by LaptopTheOne** [comment] 2022-08-11 17:19
> > Confirmed on mac that changing all occurrences of `electron-browser` to `electron-sandbox` inside `~/.vscode/extensions/robbowen.synthwave-vscode-0.1.11/src/extension.js` fixed the issue.
> 
> I tried this but am still getting the admin error. I reloaded VSCode, is there anything else I need to do to get this to work? I'm on an M1, macOS 12.4.
> 
> Also, will an update to the extension with this fix be released soon?

@bildungsroman try quitting the vscode completely and try it.

**Comment by robb0wen** [comment] 2022-08-12 10:23
I've just merged a fix for this, and a few other changes. The latest version is bumped to v0.1.14 and should fix the issues starting the glow.

Thanks everyone for your input on this!

**Comment by Jayprecode** [comment] 2022-08-12 11:29
> I'm also facing the same issue.
> 
> I've tried the solution suggested in #146 but it didn't work.
> 
> The suggested fix is to run:
> 
> `sudo chmod ugo+rw /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench`
> 
> However, `workbench` is not present inside `electron-browser` in the newer Insider builds. So, if the theme looks for it in that directory, it will error out. I have not gone through the code, but could this be the root cause of the issue?

sudo chmod ugo+rw /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench

**Comment by 61ZM07H36R3ML1N** [comment] 2022-08-13 19:33
I had to add the synthwave.css via custom css and js loader extension to get the theme working again following this guide. [the guide](https://medium.com/@nadinCodeHat/heres-how-to-install-the-synthwave-84-theme-and-activate-the-glow-effect-neon-dreams-in-vs-code-315ceeeacd39)

it worked flawlessly

**Comment by robb0wen** [comment] 2022-08-15 08:12
Closing this as the latest published version of the extension, v0.1.14 should fix the admin issue and allow the Neon Dreams command to work as normal.
 
FYI, linking the CSS via the custom CSS and JS loader hasn't been the standard approach for a while now, and should be considered as a fallback if nothing else works (it doesn't dynamically create the glow classes like core extension does).

**Closed by robb0wen** 2022-08-15 08:12 UTC

**Comment by JerryApazaYllatupa** [comment] 2022-12-18 15:29
sigo teniendo el mismo problema la extension ya esta actualizado 1.70.0 

	const electronBase = isVSCodeBelowVersion("1.70.0") ? "electron-browser" : "electron-sandbox";

		const htmlFile =
			base +
			(isWin
				? "\\"+electronBase+"\\workbench\\workbench.html"
				: "/"+electronBase+"/workbench/workbench.html");

		const templateFile =
				base +
				(isWin
					? "\\"+electronBase+"\\workbench\\neondreams.js"
					: "/"+electronBase+"/workbench/neondreams.js");

**Comment by rangeldor** [comment] 2023-01-11 14:51
> sigo teniendo el mismo problema la extension ya esta actualizado 1.70.0 y no puedo activar | enable synthwave84 neon dreams
> 
> ```
> const electronBase = isVSCodeBelowVersion("1.70.0") ? "electron-browser" : "electron-sandbox";
> 
> 	const htmlFile =
> 		base +
> 		(isWin
> 			? "\\"+electronBase+"\\workbench\\workbench.html"
> 			: "/"+electronBase+"/workbench/workbench.html");
> 
> 	const templateFile =
> 			base +
> 			(isWin
> 				? "\\"+electronBase+"\\workbench\\neondreams.js"
> 				: "/"+electronBase+"/workbench/neondreams.js");
> ```

Me too! Since before the update.
